### ISSUE TITLE
关于单例模式之双检锁加入volivate是为了防止指令重排序吗？

### ISSUE THREAD

**Issue by zhanghongwang** [qindongliang/Java-Note#1]
是否可以提供测试代码呢

**Comment by qindongliang** [comment]
确实是为了防止指令重排，但这块出现几率比较小，你可以单独验证volatile的重排序功能，这块网上例子很多

**Comment by zhanghongwang** [comment]
volatile虽然具有重排序但是也是遵循一些条件的比如有数据依赖的情况下会进行重排序，而且在加上synchronized关键字后里面代码就会变成单线程的状态，在单线程无论怎么重排序都会遵循as-if-serial语义的吧！ 之前也是怀疑这方面的问题但是怎么测试都测试不出来重排序的问题,如果说测试不出来能不能假设这样的代码是不会被重排序的

**Comment by zhanghongwang** [comment]
是的当new一个对象的时候 jvm会有以下步骤：
1.类加载,同时初始化类中静态的属性(赋默认值) 
2.执行静态代码块 
3.分配内存空间,同时初始化非静态的属性(赋默认值) 
4.调用父类构造器 
5.父类构造器执行完后,如果自己声明属性的同时有显示的赋值,那么进行显示赋值把默认值覆盖 
6.执行匿名代码块 
7.执行构造器 
8.返回内存地址
但是我理解的重排序是对我们写的程序做重排序,jvm的加载顺序不受影响的，那么如果真的按照你所说的jvm的加载顺序也会进行重排序即便是几率很小那么应该也是可以测试出来的。

**Comment by qindongliang** [comment]
对，只要有几率肯定会被测出来，但花费的时间不确定的，可能花费几分钟，也有可能几个月或者几年。

**Comment by zhanghongwang** [comment]
大神是否提供关于jvm加载顺序也会被重排序的相关学习资料。

**Comment by qindongliang** [comment]
重排序跟操作系统的CPU的指令执行原理有关系，你可以深入了解下，Java是通过JMM内存模型来屏蔽这个问题，想要进一步了解，可以学习底层的知识和操作系统的原理

**Comment by qindongliang** [comment]
这里有一篇文章，你可以参考一下：http://www.cs.umd.edu/~pugh/java/memoryModel/jsr-133-faq.html#volatile
